#### analyze microarray data generated by MAQC
library(oligo)
library(siggenes)
library(limma)

######## go to the folder with CEL files and read in raw data
CELfiles=dir(pattern="CEL.gz$")
rawdata.u133a=read.celfiles(filenames= CELfiles[1:6])
rawdata.u133plus2=read.celfiles(filenames= CELfiles[7:12])

## the rawdatas are objects of ExpressionFeatureSet class.
## to extract data from it use "exprs" function. For example,
dat=exprs(rawdata.u133a)
colnames(dat)=c(paste("Ref",1:3), paste("Brain", 1:3))
head(dat)
dim(dat)

########## quick exploratory analysis of raw data
### Students try do do this by yourselves. Examples are:
### Look and compare the marginal distribution of data,
### correlations among different samples,
### simple clustering of samples, etc.
### I have some sample codes at the end of this file.


###### normalization and summarization using RMA
normdata.u133a=rma(rawdata.u133a)
normdata.u133plus2=rma(rawdata.u133plus2)
## the normdatas are objects of ExpressionSet class.
## also use "exprs" to extract data. These are in log scales.
dat.u133a.norm=exprs(normdata.u133a)
dat.u133plus2.norm=exprs(normdata.u133plus2)
dim(dat.u133a.norm) ## notice that number of rows are greatly reduced.
boxplot(log2(dat.u133a.norm))

save(dat.u133a.norm, dat.u133plus2.norm, file="normData-microarray.rda")

##### Now we want to compare the log fold changes between two samples
## from two array platforms.
lfc.u133a=rowMeans(dat.u133a.norm[,1:3]) - rowMeans(dat.u133a.norm[,4:6])
lfc.u133plus2=rowMeans(dat.u133plus2.norm[,1:3]) - rowMeans(dat.u133plus2.norm[,4:6])

#### look at the fold changes
head(lfc.u133a)
head(lfc.u133plus2)
## since they are from two different arrays, need to pick the ones from common probesets.
commonGenes=intersect(names(lfc.u133a), names(lfc.u133plus2))
lfc1=lfc.u133a[commonGenes]
lfc2=lfc.u133plus2[commonGenes]
cor(lfc1, lfc2)
plot(lfc1, lfc2, pch=".", xlab="U133A", ylab="U133 plus2", main="Comparison of log fold changes")
abline(0,1, lwd=2, lty=2, col="red")

## The affymetrix gene names are some IDs such as 1007_s_at, 1053_at, etc.
## find the corresponding gene names (I'm using gene acronyms).
## We will use the db packages hgu133plus2.db and hgu133a.db
library(hgu133a.db)
geneNames <- as.character(hgu133aACCNUM[commonGenes])
head(geneNames)

######## now compare it to the gold standard Taqman data:
## read in taqman data
taqman=read.table("Taqman_expr.txt",header=TRUE, sep="\t")
head(taqman)
lfc.taqman=data.frame(gene=taqman$txname, lfc.taqman=log(rowMeans(taqman[,2:5]))-log(rowMeans(taqman[,6:9])))
head(lfc.taqman)

## make a data frame for microarray log fold changes
lfc.microarray=data.frame(gene=geneNames, lfc.u133a=lfc1, lfc.u133plus2=lfc2)
head(lfc.microarray)

## use merge function to combine log fold changes from different platforms on common genes.
all.lfc=merge(lfc.taqman, lfc.microarray, by="gene")
head(all.lfc)
cor(all.lfc[,2:4])
par(mfrow=c(1,2))
plot(all.lfc[,2], all.lfc[,3], pch=".", xlab="Taqman", ylab="U133A")
plot(all.lfc[,2], all.lfc[,4], pch=".", xlab="Taqman", ylab="U133 plus 2")

## it can be seen U133plus2 is better than U133A, for it has higher correlation with taqman

###########################################################
## now DE detection using limma
###########################################################
design=cbind(mu=1,beta=c(rep(0,3),rep(1,3)))

## U133A
DE.limma.u133a=lmFit(dat.u133a.norm, design=design)
DE.limma.u133a=eBayes(DE.limma.u133a)
pval.u133a=DE.limma.u133a$p.value[,"beta"]

## U133 plus2
DE.limma.u133plus2=lmFit(dat.u133plus2.norm, design=design)
DE.limma.u133plus2=eBayes(DE.limma.u133plus2)
pval.u133plus2=DE.limma.u133plus2$p.value[,"beta"]

## merge and see correlations
pval1=pval.u133a[commonGenes]
pval2=pval.u133plus2[commonGenes]
cor(pval1, pval2) ## correlations is much lower than that from fold change
cor(pval1, pval2, method="spearman") ## but the rank correlation is good
plot(pval1, pval2, pch=".", log="xy") ## okay


###########################################################################
### Use Taqman as gold standard, we can compare the DE detection from
### two platforms using ROC curves.
###########################################################################
## merge pvalues with taqman results
pval.microarray=data.frame(gene=geneNames, pval.u133a=pval1, pval.u133plus2=pval2)
all.pval=merge(lfc.taqman, pval.microarray, by="gene")
ngenes=nrow(all.pval)

## construct gold standard. From taqman, abs(lfc)>2 are deemed DE, abs(lfc)<0.2 are deemed non-DE
## the middle ones are deemed unknown.
flag=rep(NA, ngenes)
flag[abs(all.pval[,2])>2]=TRUE
flag[abs(all.pval[,2])<0.2]=FALSE
idx=which(!is.na(flag))

## a function to compute ROC curve:
library(ROCR)
ROC.DE <- function(DE.gs, pval) {
  pred = prediction(1-pval, DE.gs)
  perf = performance(pred,"tpr","fpr")
  perf
}

## compare ROC curve
ROC.u133a=ROC.DE(flag[idx], all.pval[idx,3])
ROC.u133plus2=ROC.DE(flag[idx], all.pval[idx,4])
plot(ROC.u133a, lwd=2)
plot(ROC.u133plus2, col="red", lwd=2, add=TRUE)
legend("bottomright", legend=c("U133A", "U133 plus2"), col=c("black", "red"), lty=1, lwd=2)
## almost identical in their abilities to detect DE.


############################################################
## Below are not required in the lab.
## Follow the codes in the lab, use SAM for DE detection
## Then compare the performances of SAM and limma for U133A arrays
## using ROC curves.
############################################################




#############################################
## some codes for quick exploratory analysis
#############################################

ldat=log2(dat)
hist(ldat[,1], 100) # distribution of log intensity
boxplot(ldat) # between array variation is small.
cor(ldat) # correlation among samples

## cluster the samples
hc=hclust(dist(t(ldat)))
plot(hc)

